### ISSUE TITLE
Where is all the data stored?

### ISSUE THREAD

**Issue by Theo1996** [MangaDexPP/userscript#1]
My selections keep resetting randomly or everyday almost, is it the cookies?
Firefox 91.9.1 esr

**Comment by Theo1996** [comment]
It was some of my settings on how much hdd space to allow for firefox site data, can you please make it a file that is exportable and a selection if I want to use an external file or firefox internal storage?

**Comment by dlresearchsociety** [comment]
Not cookies, [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). Feel free to open MR if you want to, and I'll review; but this feature is not something I'm interested in so I won't be personally implementing it.

Exporting is as simple as running `window.localStorage` in your browser console. Maybe convert to JSON string then do JSON parse for importing.

**Comment by Theo1996** [comment]
@dlresearchsociety  I ran window.localStorage in the console and now the button on each manga read,ignore,etc dont show up.The big buttons on top of the page with the toggles show up though.

ps I meant the latest page doesnt show buttons on every manga title.
PS I see you updated the script to 1.0.3 so it broke.
PS 1.0.2 works, wasted 20 minutes figuring this out.

**Comment by dlresearchsociety** [comment]
@Theo1996 that's weird. I made the changes in 1.0.3 since the old user element selector stopped working for me on 1.0.2. Will take a look at it later. Pro tip: check the console log to see what goes wrong for all your userscripts (sometimes the websites themselves).

**Comment by Theo1996** [comment]
Firefox 115.9 esr, maybe leave in the old user element selector and check for FF versions?
My main FF is 91.9.1 esr so it would be nice if it work there too.
>  Uncaught ReferenceError: row is not defined
>     blockUsers moz-extension://e7cec845-e706-45f3-90a5-6d6cf350aea6/userscripts/MangaDex++.user.js?id=0c20f644-9316-4b58-967b-5699c5dd7364:584
>     handleBaseUrl moz-extension://e7cec845-e706-45f3-90a5-6d6cf350aea6/userscripts/MangaDex++.user.js?id=0c20f644-9316-4b58-967b-5699c5dd7364:121
>     main moz-extension://e7cec845-e706-45f3-90a5-6d6cf350aea6/userscripts/MangaDex++.user.js?id=0c20f644-9316-4b58-967b-5699c5dd7364:113
> [latest line 9 > injectedScript:584:24](https://mangadex.org/titles/latest%20line%209%20%3E%20injectedScript)
>     blockUsers moz-extension://e7cec845-e706-45f3-90a5-6d6cf350aea6/userscripts/MangaDex++.user.js?id=0c20f644-9316-4b58-967b-5699c5dd7364:584
>     handleBaseUrl moz-extension://e7cec845-e706-45f3-90a5-6d6cf350aea6/userscripts/MangaDex++.user.js?id=0c20f644-9316-4b58-967b-5699c5dd7364:121
>     main moz-extension://e7cec845-e706-45f3-90a5-6d6cf350aea6/userscripts/MangaDex++.user.js?id=0c20f644-9316-4b58-967b-5699c5dd7364:113

**Comment by dlresearchsociety** [comment]
Yea nevermind I'm stupid. Missed one line when copied from my version. Should be fixed now

**Comment by Theo1996** [comment]
thanks it works now
